name: graphql_client
description: A Dart package for interacting with GraphQL APIs.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.3.0
  graphql_flutter: ^5.2.0

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.6.0
  test: ^1.22.0
